
import java.awt.Cursor;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vt
 */
public class LecPage extends javax.swing.JFrame {

    /**
     * Creates new form LecPage
     */
    Connection con = null;
    
    public LecPage() throws SQLException {
        initComponents();
        jLayeredPane_Home.setVisible(true);
        jLayeredPane_assignments.setVisible(false);
        jLayeredPane_settings.setVisible(false);
        jLayeredPane_users.setVisible(false);
        con = DBCon.con();
        
        String sql = "SELECT *FROM student";
        String sq = "SELECT *FROM users";
        
        Statement stmt = con.createStatement();
        stmt.execute(sql);
        ResultSet rs = stmt.executeQuery(sql);
        rs.last();
        int count = rs.getRow();
        rs.beforeFirst();
         String vv = Integer.toString(count);
         jLabel5_student.setText("You Have "+vv+" Signed in Students");
         
         
         Statement stm = con.createStatement();
        stm.execute(sql);
        ResultSet r = stmt.executeQuery(sq);
        r.last();
        int coun = r.getRow();
        r.beforeFirst();
        String v = Integer.toString(coun);
         jLabel4_assi.setText(v+" Students Submitted Assignment(s) of "+vv);
        
         
         PreparedStatement ps = con.prepareStatement("SELECT * FROM student");
         ResultSet s = ps.executeQuery();
         jTable1_users.setModel(DbUtils.resultSetToTableModel(s));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        jButton_assignments = new javax.swing.JButton();
        jButton_home = new javax.swing.JButton();
        jButton_accounts = new javax.swing.JButton();
        jButton_Settings = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        jLayeredPane_Home = new javax.swing.JLayeredPane();
        jLabel1_admin = new javax.swing.JLabel();
        jLabel3_pic = new javax.swing.JLabel();
        jLabel4_assi = new javax.swing.JLabel();
        jLabel5_student = new javax.swing.JLabel();
        jLayeredPane_assignments = new javax.swing.JLayeredPane();
        jScrollPane_assignments = new javax.swing.JScrollPane();
        jTable_assignments = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane_users = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_users = new javax.swing.JTable();
        jButton3_add = new javax.swing.JButton();
        jButton4_delete = new javax.swing.JButton();
        jButton5_upadte = new javax.swing.JButton();
        jTextField1_reg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2_fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3_sname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4_password = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5_level = new javax.swing.JTextField();
        jLayeredPane_settings = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(170);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setEnabled(false);

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jButton_assignments.setBackground(new java.awt.Color(255, 255, 255));
        jButton_assignments.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton_assignments.setText("Assignments");
        jButton_assignments.setBorder(null);
        jButton_assignments.setBorderPainted(false);
        jButton_assignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_assignmentsActionPerformed(evt);
            }
        });

        jButton_home.setBackground(new java.awt.Color(255, 255, 255));
        jButton_home.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton_home.setText("Home");
        jButton_home.setBorder(null);
        jButton_home.setBorderPainted(false);
        jButton_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_homeActionPerformed(evt);
            }
        });

        jButton_accounts.setBackground(new java.awt.Color(255, 255, 255));
        jButton_accounts.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton_accounts.setText("User Accounts");
        jButton_accounts.setBorder(null);
        jButton_accounts.setBorderPainted(false);
        jButton_accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_accountsActionPerformed(evt);
            }
        });

        jButton_Settings.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Settings.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton_Settings.setText("Settings");
        jButton_Settings.setBorder(null);
        jButton_Settings.setBorderPainted(false);
        jButton_Settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton_assignments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton_accounts, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
            .addComponent(jButton_Settings, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
            .addComponent(jButton_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton_home, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jButton_assignments, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jButton_accounts, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jButton_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        rightPanel.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1_admin.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1_admin.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1_admin.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_admin.setText("Lecturer & Admin Panel");
        jLabel1_admin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignments750.png"))); // NOI18N

        jLabel4_assi.setBackground(new java.awt.Color(0, 51, 204));
        jLabel4_assi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4_assi.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4_assi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4_assi.setText("5 Submitted Assignments");
        jLabel4_assi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 5, 1, 7, new java.awt.Color(255, 255, 255)));
        jLabel4_assi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4_assiMouseClicked(evt);
            }
        });

        jLabel5_student.setBackground(new java.awt.Color(0, 51, 204));
        jLabel5_student.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5_student.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5_student.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5_student.setText("5 Students ");
        jLabel5_student.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 5, 1, 7, new java.awt.Color(255, 255, 255)));
        jLabel5_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5_studentMouseClicked(evt);
            }
        });

        jLayeredPane_Home.setLayer(jLabel1_admin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Home.setLayer(jLabel3_pic, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Home.setLayer(jLabel4_assi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_Home.setLayer(jLabel5_student, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane_HomeLayout = new javax.swing.GroupLayout(jLayeredPane_Home);
        jLayeredPane_Home.setLayout(jLayeredPane_HomeLayout);
        jLayeredPane_HomeLayout.setHorizontalGroup(
            jLayeredPane_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3_pic, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_HomeLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jLayeredPane_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane_HomeLayout.createSequentialGroup()
                        .addComponent(jLabel5_student, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4_assi))
                    .addComponent(jLabel1_admin))
                .addGap(149, 149, 149))
        );
        jLayeredPane_HomeLayout.setVerticalGroup(
            jLayeredPane_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_HomeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1_admin)
                .addGap(69, 69, 69)
                .addGroup(jLayeredPane_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4_assi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5_student, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel3_pic))
        );

        jTable_assignments.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jTable_assignments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_assignments.setGridColor(new java.awt.Color(204, 204, 255));
        jTable_assignments.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable_assignmentsKeyReleased(evt);
            }
        });
        jScrollPane_assignments.setViewportView(jTable_assignments);

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Download All Files");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear All Assignments");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Showing Students Who submitted Assignments");

        jLayeredPane_assignments.setLayer(jScrollPane_assignments, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_assignments.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_assignments.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_assignments.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane_assignmentsLayout = new javax.swing.GroupLayout(jLayeredPane_assignments);
        jLayeredPane_assignments.setLayout(jLayeredPane_assignmentsLayout);
        jLayeredPane_assignmentsLayout.setHorizontalGroup(
            jLayeredPane_assignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_assignmentsLayout.createSequentialGroup()
                .addContainerGap(396, Short.MAX_VALUE)
                .addGroup(jLayeredPane_assignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jLayeredPane_assignmentsLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(72, 72, 72)
                        .addComponent(jButton2)))
                .addGap(29, 29, 29))
            .addGroup(jLayeredPane_assignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane_assignmentsLayout.createSequentialGroup()
                    .addComponent(jScrollPane_assignments, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 385, Short.MAX_VALUE)))
        );
        jLayeredPane_assignmentsLayout.setVerticalGroup(
            jLayeredPane_assignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_assignmentsLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addGroup(jLayeredPane_assignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(56, 56, 56))
            .addGroup(jLayeredPane_assignmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane_assignments, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
        );

        jLayeredPane_users.setForeground(new java.awt.Color(255, 255, 255));

        jTable1_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_usersMouseClicked(evt);
            }
        });
        jTable1_users.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1_usersKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1_usersKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_users);

        jButton3_add.setBackground(new java.awt.Color(0, 153, 0));
        jButton3_add.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton3_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_add.setText("Add");
        jButton3_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_addActionPerformed(evt);
            }
        });

        jButton4_delete.setBackground(new java.awt.Color(255, 0, 0));
        jButton4_delete.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton4_delete.setForeground(new java.awt.Color(255, 255, 255));
        jButton4_delete.setText("Delete");
        jButton4_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_deleteActionPerformed(evt);
            }
        });

        jButton5_upadte.setBackground(new java.awt.Color(255, 204, 0));
        jButton5_upadte.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton5_upadte.setForeground(new java.awt.Color(255, 255, 255));
        jButton5_upadte.setText("Update");
        jButton5_upadte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_upadteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RegNo");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Firstname");

        jTextField2_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_fnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lastname");

        jTextField3_sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_snameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Level");

        jLayeredPane_users.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jButton3_add, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jButton4_delete, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jButton5_upadte, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jTextField1_reg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jTextField2_fname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jTextField3_sname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jTextField4_password, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_users.setLayer(jTextField5_level, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane_usersLayout = new javax.swing.GroupLayout(jLayeredPane_users);
        jLayeredPane_users.setLayout(jLayeredPane_usersLayout);
        jLayeredPane_usersLayout.setHorizontalGroup(
            jLayeredPane_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_usersLayout.createSequentialGroup()
                .addContainerGap(467, Short.MAX_VALUE)
                .addGroup(jLayeredPane_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_usersLayout.createSequentialGroup()
                        .addComponent(jButton3_add)
                        .addGap(28, 28, 28)
                        .addComponent(jButton4_delete)
                        .addGap(33, 33, 33)
                        .addComponent(jButton5_upadte)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_usersLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jTextField1_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_usersLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jTextField2_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_usersLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jTextField3_sname, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_usersLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jTextField4_password, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_usersLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jTextField5_level, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jLayeredPane_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane_usersLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 321, Short.MAX_VALUE)))
        );
        jLayeredPane_usersLayout.setVerticalGroup(
            jLayeredPane_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_usersLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jLayeredPane_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jLayeredPane_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jLayeredPane_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3_sname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jLayeredPane_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4_password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jLayeredPane_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5_level, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jLayeredPane_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3_add)
                    .addComponent(jButton4_delete)
                    .addComponent(jButton5_upadte))
                .addGap(90, 90, 90))
            .addGroup(jLayeredPane_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Change Password");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Old Password");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("New Password");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Change Password");

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Reset System");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLayeredPane_settings.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_settings.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_settings.setLayer(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_settings.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_settings.setLayer(jPasswordField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_settings.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_settings.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane_settingsLayout = new javax.swing.GroupLayout(jLayeredPane_settings);
        jLayeredPane_settings.setLayout(jLayeredPane_settingsLayout);
        jLayeredPane_settingsLayout.setHorizontalGroup(
            jLayeredPane_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_settingsLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jLayeredPane_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane_settingsLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane_settingsLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(152, 152, 152)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jLayeredPane_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane_settingsLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(152, 152, 152)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        jLayeredPane_settingsLayout.setVerticalGroup(
            jLayeredPane_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane_settingsLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(jLayeredPane_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jLayeredPane_settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane_Home, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane_assignments))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane_users))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane_settings))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane_Home)
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane_assignments))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane_users, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane_settings))
        );

        jSplitPane1.setRightComponent(rightPanel);

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_homeActionPerformed
        try {
            // TODO add your handling code here:
            jLayeredPane_Home.setVisible(true);
            jLayeredPane_assignments.setVisible(false);
            jLayeredPane_settings.setVisible(false);
            jLayeredPane_users.setVisible(false);
            
            
            
            
            String sql = "SELECT *FROM student";
            String sq = "SELECT *FROM users";
            
            Statement stmt = con.createStatement();
            stmt.execute(sql);
            ResultSet rs = stmt.executeQuery(sql);
            rs.last();
            int count = rs.getRow();
            rs.beforeFirst();
            String vv = Integer.toString(count);
            jLabel5_student.setText("You Have "+vv+" Signed in Students");
            
            
            Statement stm = con.createStatement();
            stm.execute(sql);
            ResultSet r = stmt.executeQuery(sq);
            r.last();
            int coun = r.getRow();
            r.beforeFirst();
            String v = Integer.toString(coun);
            jLabel4_assi.setText(v+" Students Submitted Assignment(s) of "+vv);
            
            
            PreparedStatement ps = con.prepareStatement("SELECT * FROM student");
            ResultSet s = ps.executeQuery();
            jTable1_users.setModel(DbUtils.resultSetToTableModel(s));
        } catch (SQLException ex) {
            Logger.getLogger(LecPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_homeActionPerformed

    private void jButton_assignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_assignmentsActionPerformed
        try {
            // TODO add your handling code here:
            jLayeredPane_Home.setVisible(false);
            jLayeredPane_assignments.setVisible(true);
            jLayeredPane_settings.setVisible(false);
            jLayeredPane_users.setVisible(false);
            PreparedStatement p = con.prepareStatement("SELECT RegNo FROM users");
            ResultSet s = p.executeQuery();
            jTable_assignments.setModel(DbUtils.resultSetToTableModel(s));
        } catch (SQLException ex) {
            Logger.getLogger(LecPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_assignmentsActionPerformed

    private void jButton_accountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_accountsActionPerformed
        // TODO add your handling code here:
         jLayeredPane_Home.setVisible(false);
        jLayeredPane_assignments.setVisible(false);
        jLayeredPane_settings.setVisible(false);
        jLayeredPane_users.setVisible(true);
        jTextField1_reg.setText("");
        jTextField3_sname.setText("");
        jTextField2_fname.setText("");
        jTextField4_password.setText("");
        jTextField5_level.setText("");
    }//GEN-LAST:event_jButton_accountsActionPerformed

    private void jButton_SettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SettingsActionPerformed
        // TODO add your handling code here:
         jLayeredPane_Home.setVisible(false);
        jLayeredPane_assignments.setVisible(false);
        jLayeredPane_settings.setVisible(true);
        jLayeredPane_users.setVisible(false);
    }//GEN-LAST:event_jButton_SettingsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
		Statement myStmt = null;
		ResultSet myRs = null;

		InputStream input = null;
		FileOutputStream output = null;

		try {
			

			// 2. Execute statement
			myStmt = con.createStatement();
			String sql = "select file from users";
			myRs = myStmt.executeQuery(sql);
			
			// 3. Set up a handle to the file
			
                        
                        myRs.last();
                        int count = myRs.getRow();
                        myRs.beforeFirst();
                        //System.out.println("will read "+count+"files");
//                        //System.out.println(count);
//                        int lengthq = String.valueOf(count).length();
//                        System.out.println(lengthq);
                         int []arr = new int[count];
                         
                         for(int i=0;i<arr.length;i++){
                            
                             File theFile = new File("pdf_from_db"+i+".pdf");
                            output = new FileOutputStream(theFile);
                            
                            if (myRs.next()) {

				input = myRs.getBinaryStream("file"); 
                                
				//System.out.println("Reading file from database...");
				//System.out.println(sql);
                                

				
				byte[] buffer = new byte[1024];
				while (input.read(buffer) > 0) {
					output.write(buffer);
				}
				JOptionPane.showMessageDialog(this,"\nSaved "+i+"file(s) to: " + theFile.getAbsolutePath()+ "\nCompleted successfully!");
                                
			}
                            
                            
                            
                         }
                         
			

		} catch (Exception exc) {
			exc.printStackTrace();}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            
            PreparedStatement pss = con.prepareStatement("TRUNCATE `manager`.`users`");
              pss.execute();
            JOptionPane.showMessageDialog(this, "All received assignments have been cleared!!");
            
            PreparedStatement p = con.prepareStatement("SELECT RegNo FROM users");
            ResultSet s = p.executeQuery();
            jTable_assignments.setModel(DbUtils.resultSetToTableModel(s));
            
        } catch (SQLException ex) {
            Logger.getLogger(LecPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel5_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5_studentMouseClicked
        // TODO add your handling code here:
        jLayeredPane_users.setVisible(true);
        jLayeredPane_Home.setVisible(false);
        jLayeredPane_assignments.setVisible(false);
        jLayeredPane_settings.setVisible(false);
    }//GEN-LAST:event_jLabel5_studentMouseClicked

    private void jLabel4_assiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4_assiMouseClicked
        // TODO add your handling code here:
        jLayeredPane_users.setVisible(false);
        jLayeredPane_Home.setVisible(false);
        jLayeredPane_assignments.setVisible(true);
        jLayeredPane_settings.setVisible(false);
    }//GEN-LAST:event_jLabel4_assiMouseClicked

    private void jTable1_usersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1_usersKeyPressed
        
    }//GEN-LAST:event_jTable1_usersKeyPressed

    private void jTextField2_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_fnameActionPerformed

    private void jTextField3_snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_snameActionPerformed

    private void jButton5_upadteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_upadteActionPerformed
        try {
            // TODO add your handling code here:
            String reg = jTextField1_reg.getText();
            String name = jTextField2_fname.getText();
            String sname = jTextField3_sname.getText();
            String pass = jTextField4_password.getText();
            String year = jTextField5_level.getText();
            
            
            String sql = "UPDATE student SET first_name='"+name+"', last_name='"+sname+"', password='"+pass+"', level='"+year+"'  WHERE regNo = '"+reg+"'";
            
            PreparedStatement ps = con.prepareStatement(sql);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, reg+" Updated!!");
            
            
            PreparedStatement p = con.prepareStatement("SELECT * FROM student");
            ResultSet s = p.executeQuery();
            jTable1_users.setModel(DbUtils.resultSetToTableModel(s));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jButton5_upadteActionPerformed

    private void jTable1_usersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1_usersKeyReleased
        // TODO add your handling code here:
        int i = jTable1_users.getSelectedRow();
        TableModel model = jTable1_users.getModel();

        
        jTextField1_reg.setText(model.getValueAt(i, 0).toString());
        jTextField2_fname.setText(model.getValueAt(i,1).toString());
        jTextField3_sname.setText(model.getValueAt(i,2 ).toString());
        jTextField4_password.setText(model.getValueAt(i, 3).toString());
        jTextField5_level.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jTable1_usersKeyReleased

    private void jTable1_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_usersMouseClicked
        // TODO add your handling code here:
        int i = jTable1_users.getSelectedRow();
        TableModel model = jTable1_users.getModel();

        
        jTextField1_reg.setText(model.getValueAt(i, 0).toString());
        jTextField2_fname.setText(model.getValueAt(i,1).toString());
        jTextField3_sname.setText(model.getValueAt(i,2 ).toString());
        jTextField4_password.setText(model.getValueAt(i, 3).toString());
        jTextField5_level.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jTable1_usersMouseClicked

    private void jButton4_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_deleteActionPerformed
        try {
            // TODO add your handling code here:
            String reg = jTextField1_reg.getText();
            String sql = "DELETE FROM student WHERE regNo = '"+reg+"'";
            
            PreparedStatement ps = con.prepareStatement(sql);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, reg+" Deleted");
            
            
            PreparedStatement p = con.prepareStatement("SELECT * FROM student");
            ResultSet s = p.executeQuery();
            jTable1_users.setModel(DbUtils.resultSetToTableModel(s));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }//GEN-LAST:event_jButton4_deleteActionPerformed

    private void jTable_assignmentsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable_assignmentsKeyReleased
        try {
            // TODO add your handling code here:
            PreparedStatement p = con.prepareStatement("SELECT RegNo FROM users");
            ResultSet s = p.executeQuery();
            jTable_assignments.setModel(DbUtils.resultSetToTableModel(s));
        } catch (SQLException ex) {
            Logger.getLogger(LecPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable_assignmentsKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            PreparedStatement pss = con.prepareStatement("TRUNCATE `manager`.`users`");
            pss.execute();
            
            PreparedStatement psAs = con.prepareStatement("TRUNCATE `manager`.`student`");
            psAs.execute();
            
            JOptionPane.showMessageDialog(this, "All Users & Assignments have been Deleted!!");
        } catch (SQLException ex) {
            //Logger.getLogger(LecPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_addActionPerformed
        PreparedStatement ps = null;
        try {
            String reg = jTextField1_reg.getText();
            String name = jTextField2_fname.getText();
            String sname = jTextField4_password.getText();
            String year = jTextField5_level.getText();
            ps = con.prepareStatement("INSERT INTO stud(?,?,?,?)");
            ps.setString(1, reg);
            ps.setString(2, name);
            ps.setString(3, sname);
            ps.setString(4, year);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } 
    }//GEN-LAST:event_jButton3_addActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
        Login obj = new Login();
        obj.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LecPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LecPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LecPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LecPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LecPage().setVisible(true);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3_add;
    private javax.swing.JButton jButton4_delete;
    private javax.swing.JButton jButton5_upadte;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_Settings;
    private javax.swing.JButton jButton_accounts;
    private javax.swing.JButton jButton_assignments;
    private javax.swing.JButton jButton_home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_admin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_pic;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4_assi;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5_student;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane_Home;
    private javax.swing.JLayeredPane jLayeredPane_assignments;
    private javax.swing.JLayeredPane jLayeredPane_settings;
    private javax.swing.JLayeredPane jLayeredPane_users;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_assignments;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1_users;
    private javax.swing.JTable jTable_assignments;
    private javax.swing.JTextField jTextField1_reg;
    private javax.swing.JTextField jTextField2_fname;
    private javax.swing.JTextField jTextField3_sname;
    private javax.swing.JTextField jTextField4_password;
    private javax.swing.JTextField jTextField5_level;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
